# **Financial Market News Prediction using Random Forest Classifier**

## **Objective**
The goal of this project is to predict financial market movements (up/down) based on daily news headlines using a machine learning model. We aim to classify whether the market will go up or down based on news data using a **Random Forest Classifier**.

## **Data Source**
- The dataset is sourced from a CSV file available at: [Financial Market News Dataset](https://github.com/YBIFoundation/Dataset/blob/main/Financial%20Market%20News.csv)

## **Import Libraries**

In [2]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

## **Data Import**

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/YBIFoundation/Dataset/main/Financial%20Market%20News.csv', encoding="ISO-8859-1")

## **Data Visualization**

In [5]:
df.head()

,Date,Label,News 1,News 2,News 3,News 4,News 5,News 6,News 7,News 8,...,News 16,News 17,News 18,News 19,News 20,News 21,News 22,News 23,News 24,News 25
0,01-01-2010,0,McIlroy's men catch cold from Gudjonsson,Obituary: Brian Walsh,Workplace blues leave employers in the red,Classical review: Rattle,Dance review: Merce Cunningham,Genetic tests to be used in setting premiums,Opera review: La Bohème,Pop review: Britney Spears,...,Finland 0 - 0 England,Healy a marked man,Happy birthday Harpers & Queen,Win unlimited access to the Raindance film fes...,Labour pledges £800m to bridge north-south divide,Wales: Lib-Lab pact firm despite resignation,Donald Dewar,Regenerating homes regenerates well-being in ...,Win £100 worth of underwear,TV guide: Random views
1,02-01-2010,0,Warning from history points to crash,Investors flee to dollar haven,Banks and tobacco in favour,Review: Llama Farmers,War jitters lead to sell-off,Your not-so-secret history,Review: The Northern Sinfonia,Review: Hysteria,...,Why Wenger will stick to his Gunners,Out of luck England hit rock bottom,Wilkinson out of his depth,Kinsella sparks Irish power play,Brown banished as Scots rebound,Battling Wales cling to lifeline,Ehiogu close to sealing Boro move,Man-to-man marking,Match stats,French referee at centre of storm is no strang...
2,03-01-2010,0,Comment: Why Israel's peaceniks feel betrayed,Court deals blow to seizure of drug assets,An ideal target for spooks,World steps between two sides intent on war,What the region's papers say,Comment: Fear and rage in Palestine,Poverty and resentment fuels Palestinian fury,Republican feud fear as dissident is killed,...,FTSE goes upwardly mobile,At this price? BP Amoco,Go fish,Bosnian Serb blows himself up to evade law,Orange float delayed to 2001,"Angry factory workers root out fear, favours a...",Smith defied advice on dome payout,Xerox takes the axe to jobs,Comment: Refugees in Britain,Maverick who sparked the new intifada
3,04-01-2010,1,"£750,000-a-goal Weah aims parting shot",Newcastle pay for Fletcher years,Brown sent to the stands for Scotland qualifier,Tourists wary of breaking new ground,Canary Wharf climbs into the FTSE 100,Review: Bill Bailey,Review: Classical,Review: New Contemporaries 2000,...,More cash on way for counties,Cairns carries Kiwis to victory,Year of Blanchflower's flourish when Spurs sto...,New direct approach brings only pay-per-blues,Third Division round-up,Second Division round-up,First Division round-up,McLean ends his career with a punch,Heskey grabs triple crown,Weah on his way as City march on
4,05-01-2010,1,Leeds arrive in Turkey to the silence of the fans,One woman's vision offers loan lifeline,Working Lives: How world leaders worked,Working Lives: Tricks of the trade,"Working Lives: six-hour days, long lunches and...",Pop review: We Love UK,World music review: Marisa Monte,Art review: Hollingsworth/Heyer,...,Duisenberg in double trouble,Pru to cut pension charges,Art review: Paul Graham,Shearer shot sparks Boro humiliation,Ridsdale's lingering fears as Leeds revisit Tu...,Champions League: Rangers v Galatasaray,Champions League: Lazio v Arsenal,Lazio 1 - 1 Arsenal,England in Pakistan,England given olive-branch reception

In [6]:
df.describe()

             Label
count  4101.000000
mean      0.528164
std       0.499267
min       0.000000
25%       0.000000
50%       1.000000
75%       1.000000
max       1.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4101 entries, 0 to 4100
Data columns (total 27 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Date     4101 non-null   object
 1   Label    4101 non-null   int64
 2   News 1   4101 non-null   object
 3   News 2   4101 non-null   object
 4   News 3   4101 non-null   object
 5   News 4   4101 non-null   object
 6   News 5   4101 non-null   object
 7   News 6   4101 non-null   object
 8   News 7   4101 non-null   object
 9   News 8   4101 non-null   object
 10  News 9   4101 non-null   object
 11  News 10  4101 non-null   object
 12  News 11  4101 non-null   object
 13  News 12  4101 non-null   object
 14  News 13  4101 non-null   object
 15  News 14  4101 non-null   object
 16  News 15  4101 non-null   object
 17  News 16  4101 non-null   object
 18  News 17  4101 non-null   object
 19  News 18  4101 non-null   object
 20  News 19  4101 non-null   object
 21  News 20  4101 non-null   object
 22  News 21  4101 non-null   object
 23  News 22  4101 non-null   object
 24  News 23  4100 non-null   object
 25  News 24  4098 non-null   object
 26  News 25  4098 non-null   object
dtypes: int64(1), object(26)
memory usage: 865.2+ KB

In [8]:
df.isnull().sum()

Date       0
Label      0
News 1     0
News 2     0
News 3     0
News 4     0
News 5     0
News 6     0
News 7     0
News 8     0
News 9     0
News 10    0
News 11    0
News 12    0
News 13    0
News 14    0
News 15    0
News 16    0
News 17    0
News 18    0
News 19    0
News 20    0
News 21    0
News 22    0
News 23    1
News 24    3
News 25    3
dtype: int64

In [9]:
df.shape

(4101, 27)

In [10]:
df.columns

Index(['Date', 'Label', 'News 1', 'News 2', 'News 3', 'News 4', 'News 5',
       'News 6', 'News 7', 'News 8', 'News 9', 'News 10', 'News 11', 'News 12',
       'News 13', 'News 14', 'News 15', 'News 16', 'News 17', 'News 18',
       'News 19', 'News 20', 'News 21', 'News 22', 'News 23', 'News 24',
       'News 25'],
      dtype='object')

## **Data Preprocessing**

In [12]:
# Combining all news columns into one for each row
news = []
for row in range(0, len(df.index)):
    news.append(' '.join(str(x) for x in df.iloc[row, 2:27]))

In [13]:
Cv = CountVectorizer(lowercase=True, ngram_range=(1,1))
x = Cv.fit_transform(news)

In [14]:
x.shape

(4101, 48527)

## **Data Target Variables**

In [15]:
y = df['Label']
y.shape

(4101,)

## **Train-Test Split**

In [16]:
# Splitting data into training and testing sets (70% train, 30% test)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, stratify=y, random_state=2529)

## **Modeling**

In [17]:
# Model: Random Forest Classifier
rf = RandomForestClassifier(n_estimators=200)
rf.fit(x_train, y_train)

RandomForestClassifier(n_estimators=200)

## **Model Evaluation**

In [18]:
# Making predictions on the test set
y_pred = rf.predict(x_test)

In [19]:
# Evaluation using confusion matrix and classification report
confusion_matrix(y_test, y_pred)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.45      0.24      0.31       581
           1       0.52      0.73      0.61       650

    accuracy                           0.50      1231
   macro avg       0.48      0.49      0.46      1231
weighted avg       0.49      0.50      0.47      1231

## **Prediction**

In [22]:
# Predictions made using the trained model (already done with y_pred)
y_pred

array([1, 1, 0, ..., 1, 0, 1])

## **Explanation**
1. **Text Preprocessing**: All the news columns were merged into a single text feature for each day. This is done to allow the text to be vectorized into a format that can be used by the machine learning model.

2. **Text Vectorization**: We used **CountVectorizer**, which implements a **Bag of Words (BoW)** model to convert the text into numerical vectors. This model transforms each document (in this case, a day’s news) into a vector of word counts.

3. **Model**: A **Random Forest Classifier** with 200 estimators was trained on the training data. Random Forest is an ensemble learning method that builds multiple decision trees and combines their output to improve accuracy and prevent overfitting.

4. **Model Performance**: The model is evaluated using precision, recall, F1-score, and accuracy metrics. The classification report provides a detailed breakdown of the performance for each class (0 and 1).

5. **Application**: This approach can be applied to real-time financial news to predict market movements, aiding traders and investors in decision-making processes.